# -*- coding: utf-8 -*-
"""MLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_B_JlgNssyk-buPNNNPOICt2ZGW-HSu

Setup, data, model, checkpoints, auto-resume
"""

import os, re, glob, shutil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout, BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.regularizers import l2
from google.colab import drive

# Mounting Drive (To get the data)
drive.mount('/content/drive', force_remount=False)

print(f"TF Version: {tf.__version__}")
print(f"GPUs Available: {len(tf.config.list_physical_devices('GPU'))}")

# Original Drive Path
DRIVE_PATH = '/content/drive/MyDrive/archive/FOREST_FIRE_SMOKE_AND_NON_FIRE_DATASET'

# New Local Path (Saving in Colab)
LOCAL_PATH = '/content/local_dataset'

if not os.path.exists(LOCAL_PATH):
    print("Copying dataset from Drive to Local Disk...")
    !cp -r "$DRIVE_PATH" "$LOCAL_PATH"
    print("Copy complete!")
else:
    print("Data already exists on local disk. Skipping copy.")


TRAIN_DIR = os.path.join(LOCAL_PATH, 'train')
TEST_DIR  = os.path.join(LOCAL_PATH, 'test')

IMG_SIZE = (64, 64)
BATCH_SIZE = 32
TOTAL_EPOCHS = 30
SEED = 42
L2_REG = 0.001

np.random.seed(SEED)
tf.random.set_seed(SEED)

# Checkpoint directories
CHECKPOINT_WEIGHTS_DIR = "/content/drive/MyDrive/mlp_checkpoints"
CHECKPOINT_FULL_DIR = "/content/drive/MyDrive/mlp_checkpoints_full"
PLOT_DIR = "/content/drive/MyDrive/mlp_analysis_plots"
FINAL_MODEL_PATH = "/content/drive/MyDrive/wildfire_mlp_model_final.h5"

os.makedirs(CHECKPOINT_WEIGHTS_DIR, exist_ok=True)
os.makedirs(CHECKPOINT_FULL_DIR, exist_ok=True)
os.makedirs(PLOT_DIR, exist_ok=True)

train_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.12,
    height_shift_range=0.12,
    shear_range=0.12,
    zoom_range=0.12,
    horizontal_flip=True,
    fill_mode='nearest'
)

test_gen = ImageDataGenerator(rescale=1./255)

train_data = train_gen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True,
    seed=SEED
)

test_data = test_gen.flow_from_directory(
    TEST_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

class_names = list(train_data.class_indices.keys())
num_classes = len(class_names)
print("Classes detected:", class_names)

def build_mlp(num_classes, input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3)):
    model = Sequential([
        Flatten(input_shape=input_shape),

        # Layer 1
        Dense(256, kernel_regularizer=l2(L2_REG), use_bias=False),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        Dropout(0.5),

        # Layer 2
        Dense(128, kernel_regularizer=l2(L2_REG), use_bias=False),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        Dropout(0.4),

        # Layer 3
        Dense(64, kernel_regularizer=l2(L2_REG), use_bias=False),
        BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        Dropout(0.3),

        # Output
        Dense(num_classes, activation='softmax')
    ])

    model.compile(
        optimizer=Adam(learning_rate=1e-4),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

model = build_mlp(num_classes)
model.summary()

# Checkpoint Callbacks & Resuming
weights_tpl = os.path.join(CHECKPOINT_WEIGHTS_DIR, "cp-{epoch:02d}.weights.h5")
full_tpl = os.path.join(CHECKPOINT_FULL_DIR, "model-{epoch:02d}.h5")
weights_cb = ModelCheckpoint(filepath=weights_tpl, save_weights_only=True, save_freq='epoch', verbose=1)
full_cb = ModelCheckpoint(filepath=full_tpl, save_weights_only=False, save_freq='epoch', verbose=1)
es_cb = EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True, verbose=1)
rlr_cb = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=4, verbose=1)

pattern = os.path.join(CHECKPOINT_WEIGHTS_DIR, "cp-*.weights.h5")
files = glob.glob(pattern)
initial_epoch = 0

if files:
    pairs = []
    for f in files:
        m = re.search(r'cp-(\d+)\.weights\.h5$', f)
        if m:
            pairs.append((int(m.group(1)), f))
    if pairs:
        pairs.sort(key=lambda x: x[0])
        last_epoch, latest_file = pairs[-1]
        print(f"Found checkpoint: {latest_file} (Epoch {last_epoch})")
        try:
            model.load_weights(latest_file)
            initial_epoch = last_epoch
            print(f"Successfully loaded weights. Resuming from epoch {initial_epoch}")
        except Exception as e:
            print(f"Architecture changed or load failed ({e}). Training from scratch.")
else:
    print("No checkpoints found. Training from scratch.")

"""Train, evaluate + save final model + basic plots"""

if initial_epoch >= TOTAL_EPOCHS:
    print(f"Already finished training up to epoch {initial_epoch}. Set TOTAL_EPOCHS higher to continue.")
else:
    print("Starting training... Watch the 'ms/step' time. It should be fast now!")
    history = model.fit(
        train_data,
        epochs=TOTAL_EPOCHS,
        initial_epoch=initial_epoch,
        validation_data=test_data,
        callbacks=[weights_cb, full_cb, es_cb, rlr_cb],
        verbose=1
    )

# Evaluating on test set
print("\nEvaluating on Test Set...")
test_loss, test_acc = model.evaluate(test_data, verbose=2)
print(f"\nFinal Test Loss: {test_loss:.4f}  Test Accuracy: {test_acc:.4f}")

# Saving final model
model.save(FINAL_MODEL_PATH)
print("Saved final model to:", FINAL_MODEL_PATH)

# Plotting training curves and save
if 'history' in globals() and history is not None:
    df_hist = pd.DataFrame(history.history)
    fig = df_hist.plot(figsize=(10,6)).get_figure()
    fig.suptitle("Training history")
    fig.savefig(os.path.join(PLOT_DIR, "training_history.png"))
    plt.close(fig)
    print("Saved training history to:", os.path.join(PLOT_DIR, "training_history.png"))

    plt.figure(figsize=(10,4))
    plt.subplot(1,2,1)
    plt.plot(df_hist['accuracy'], label='train_acc')
    plt.plot(df_hist['val_accuracy'], label='val_acc')
    plt.legend(); plt.title("Accuracy"); plt.grid()
    plt.subplot(1,2,2)
    plt.plot(df_hist['loss'], label='train_loss')
    plt.plot(df_hist['val_loss'], label='val_loss')
    plt.legend(); plt.title("Loss"); plt.grid()
    plt.tight_layout()
    plt.savefig(os.path.join(PLOT_DIR, "acc_loss.png"))
    plt.show()
    print("Saved acc/loss plot to:", os.path.join(PLOT_DIR, "acc_loss.png"))
else:
    print("No history found (training skipped).")

import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
from sklearn.preprocessing import label_binarize
import itertools
from PIL import Image

test_data.reset()

y_probs = model.predict(test_data, verbose=1)
y_pred = np.argmax(y_probs, axis=1)
y_true = test_data.classes

# Saving predictions DataFrame
filenames = np.array(test_data.filenames)
pred_df = pd.DataFrame({
    'filename': filenames,
    'true': [class_names[i] for i in y_true],
    'pred': [class_names[i] for i in y_pred]
})
pred_df.to_csv(os.path.join(PLOT_DIR, "predictions_table.csv"), index=False)
print("Saved predictions table to:", os.path.join(PLOT_DIR, "predictions_table.csv"))

#Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
cm_path = os.path.join(PLOT_DIR, "confusion_matrix.png")
plt.savefig(cm_path)
plt.show()
print("Saved confusion matrix to:", cm_path)

print("\nClassification Report:\n")
report = classification_report(y_true, y_pred, target_names=class_names)
print(report)
with open(os.path.join(PLOT_DIR, "classification_report.txt"), 'w') as f:
    f.write(report)
print("Saved classification report to:", os.path.join(PLOT_DIR, "classification_report.txt"))

# Accuracy from confusion matrix
per_class_acc = {}
for i, label in enumerate(class_names):
    true_count = cm[i].sum()
    correct = cm[i, i]
    per_class_acc[label] = float(correct) / true_count if true_count > 0 else 0.0

print("Per-class accuracy (recall):", per_class_acc)
pd.Series(per_class_acc).to_csv(os.path.join(PLOT_DIR, "per_class_accuracy.csv"))
print("Saved per-class accuracy to:", os.path.join(PLOT_DIR, "per_class_accuracy.csv"))

y_true_bin = label_binarize(y_true, classes=list(range(num_classes)))
fpr = dict(); tpr = dict(); roc_auc = dict()
plt.figure(figsize=(8,6))
for i in range(num_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], y_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])
    plt.plot(fpr[i], tpr[i], lw=2, label=f"{class_names[i]} (AUC = {roc_auc[i]:.3f})")

plt.plot([0,1], [0,1], 'k--', lw=1)
plt.xlim([0.0, 1.0]); plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
plt.title("Multiclass ROC - One vs Rest")
plt.legend(loc="lower right")
roc_path = os.path.join(PLOT_DIR, "roc_multiclass.png")
plt.savefig(roc_path)
plt.show()
print("Saved ROC plot to:", roc_path)

mis_idx = np.where(y_pred != y_true)[0]
print(f"Total misclassified: {len(mis_idx)} / {len(y_true)}")

n_show = min(12, len(mis_idx))
plt.figure(figsize=(16, 3 * (n_show//4 + 1)))
for i in range(n_show):
    idx = mis_idx[i]
    img_path = os.path.join(TEST_DIR, filenames[idx])
    try:
        img = keras.preprocessing.image.load_img(img_path, target_size=IMG_SIZE)
        arr = keras.preprocessing.image.img_to_array(img) / 255.0
    except Exception as e:
        img = Image.open(img_path).convert('RGB').resize(IMG_SIZE)
        arr = np.array(img) / 255.0

    top3_idx = np.argsort(y_probs[idx])[::-1][:3]
    top3 = [(class_names[j], float(y_probs[idx][j])) for j in top3_idx]

    plt.subplot((n_show+3)//4, 4, i+1)
    plt.imshow(arr)
    plt.axis('off')
    title = f"T: {class_names[y_true[idx]]}\nP: {class_names[y_pred[idx]]}\nTop3: " + ", ".join([f"{c}:{p:.2f}" for c,p in top3])
    plt.title(title, fontsize=9)

mis_path = os.path.join(PLOT_DIR, "misclassified_examples.png")
plt.tight_layout()
plt.savefig(mis_path)
plt.show()
print("Saved misclassified examples to:", mis_path)

correct_idx = np.where(y_pred == y_true)[0]
n_ok = min(12, len(correct_idx))
plt.figure(figsize=(16, 3 * (n_ok//4 + 1)))
for i in range(n_ok):
    idx = correct_idx[i]
    img_path = os.path.join(TEST_DIR, filenames[idx])
    try:
        img = keras.preprocessing.image.load_img(img_path, target_size=IMG_SIZE)
        arr = keras.preprocessing.image.img_to_array(img) / 255.0
    except:
        img = Image.open(img_path).convert('RGB').resize(IMG_SIZE)
        arr = np.array(img) / 255.0

    plt.subplot((n_ok+3)//4, 4, i+1)
    plt.imshow(arr)
    plt.axis('off')
    plt.title(f"True:{class_names[y_true[idx]]} Pred:{class_names[y_pred[idx]]}", fontsize=9)
ok_path = os.path.join(PLOT_DIR, "correct_examples.png")
plt.tight_layout()
plt.savefig(ok_path)
plt.show()
print("Saved correct examples to:", ok_path)

print("\nAll analysis outputs saved under:", PLOT_DIR)