# -*- coding: utf-8 -*-
"""image_models.ipynb

Automatically generated by Colab.

"""

import tensorflow as tf
from tensorflow.keras.optimizers import Adam
print(tf.__version__)

import matplotlib.pyplot as plt
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir('/content/drive/MyDrive'))
print("Num GPUs available:", len(tf.config.list_physical_devices('GPU')))

print(os.listdir('/content/drive/MyDrive/forest_fire_dataset/FOREST_FIRE_SMOKE_AND_NON_FIRE_DATASET/test'))

# helper function to check if images corrupted or not in dataset
from PIL import Image
import imghdr # To check image format

def find_corrupted_images(directory):
    corrupted_files = []
    print(f"Checking directory: {directory}")
    for root, _, files in os.walk(directory):
        for file in files:
            filepath = os.path.join(root, file)
            # Attempting to identify the image type first
            img_type = imghdr.what(filepath)
            if img_type is None and not file.lower().endswith(('.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff')):
                # Skips if it's clearly not an image file type and imghdr can't identify it
                continue
            try:
                with Image.open(filepath) as img:
                    img.verify() # Verifies that it is an image

            except (IOError, SyntaxError, Image.UnidentifiedImageError) as e:
                print(f"Corrupted or unidentifiable file found: {filepath} - Error: {e}")
                corrupted_files.append(filepath)
    return corrupted_files


corrupted_train = find_corrupted_images(train_dir)
corrupted_test = find_corrupted_images(test_dir)

if not corrupted_train and not corrupted_test:
    print("No corrupted or unidentifiable image files found in the specified directories.")
else:
    print("\nSummary of corrupted/unidentifiable files:")
    for f in corrupted_train:
        print(f"  Training: {f}")
    for f in corrupted_test:
        print(f"  Testing: {f}")

from tensorflow.keras.preprocessing.image import ImageDataGenerator

img_size = (128, 128)  # we can adjust the size of img and batch as we want
batch_size = 32

train_dir = '/content/drive/MyDrive/forest_fire_dataset/FOREST_FIRE_SMOKE_AND_NON_FIRE_DATASET/train'
test_dir = '/content/drive/MyDrive/forest_fire_dataset/FOREST_FIRE_SMOKE_AND_NON_FIRE_DATASET/test'

train_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'

)
test_gen = ImageDataGenerator(rescale=1./255)

train_data = train_gen.flow_from_directory(
    train_dir,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='categorical'
)
test_data = test_gen.flow_from_directory(
    test_dir,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=False
)

#Verify class indices mapping and images counts

print("Class indices mapping:", train_data.class_indices)
print("Total train samples:", train_data.samples)
print("Total test samples:", test_data.samples)
for class_name, idx in train_data.class_indices.items():
    count = len(os.listdir(os.path.join(train_dir, class_name)))
    print(f"Train class '{class_name}': {count}")
for class_name, idx in test_data.class_indices.items():
    count = len(os.listdir(os.path.join(test_dir, class_name)))
    print(f"Test class '{class_name}': {count}")

#testing if the images are loaded properly or not


images, labels = next(train_data)  # Gets a batch of images and labels

class_names = list(train_data.class_indices.keys())  # ['Smoke', 'fire', 'non fire']

plt.figure(figsize=(10,10))
for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(images[i])
    plt.title(class_names[np.argmax(labels[i])])
    plt.axis('off')
plt.show()

# Builds a Sequential CNN model
from tensorflow.keras.layers import Dropout
model = tf.keras.models.Sequential([
    # First convolutional layer: learns 32 filters, each 3x3 in size
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(128, 128, 3)),
    # Reduce size with MaxPooling (picks the brightest pixel in each 2x2 window)
    tf.keras.layers.MaxPooling2D(2, 2),

    # Second convolutional layer: learns 64 filters
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    # third layer: 128 filters
    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    # Flatten 3D features to 1D (to connect to dense layers)
    tf.keras.layers.Flatten(),
    Dropout(0.5),  # Dropout to prevent memorization (overfitting)

    # Fully connected layer with 128 neurons
    tf.keras.layers.Dense(512, activation='relu'),
    Dropout(0.5),
    # Output layer: 3 units (fire, smoke, non fire) with softmax for probability
    tf.keras.layers.Dense(3, activation='softmax')
])

model.compile(
    optimizer= Adam(learning_rate=0.0001),          # popular, efficient optimizer
    loss='categorical_crossentropy',              # loss for multi-class problems
    metrics=['accuracy']                          # track accuracy during train/test
)
model.summary()   # Prints a table showing what each layer is and how many parameters are trained there

# Saves checkpoints after every epoch in case of interrupt
checkpoint_path = '/content/drive/MyDrive/model_checkpoints/cp-{epoch:02d}.weights.h5'

# Ensures the directory exists
checkpoint_dir = os.path.dirname(checkpoint_path)
if not os.path.exists(checkpoint_dir):
    os.makedirs(checkpoint_dir)

cp_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path,
    save_weights_only=True,
    verbose=1,
    save_freq='epoch'
)

from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

import glob
import re

checkpoint_dir = '/content/drive/MyDrive/model_checkpoints'
checkpoint_files = glob.glob(os.path.join(checkpoint_dir, 'cp-*.weights.h5'))

def extract_epoch(filename):
    match = re.search(r'cp-(\d+)\.weights\.h5', filename)
    return int(match.group(1)) if match else -1

if checkpoint_files:
    latest_checkpoint = max(checkpoint_files, key=extract_epoch)
    print("Loading weights from:", latest_checkpoint)
    model.load_weights(latest_checkpoint)
else:
    print("No checkpoint found, starting from scratch.")

# Training the model
history = model.fit(
    train_data,              # the training data batches
    epochs=10,                # number of times our model will seetraining images
    callbacks=[cp_callback, early_stop]  # This saves progress after every epoch with early stop

)

# Save the full model
model.save('/content/drive/MyDrive/my_forest_fire_model3.keras')

# Then load model
from tensorflow import keras
model = keras.models.load_model('/content/drive/MyDrive/my_forest_fire_model3.keras')
model.compile(
    optimizer= Adam(learning_rate=0.0005),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
model.summary()

#Evaluate Accuracy and Loss
loss, accuracy = model.evaluate(test_data, verbose=1)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

#Predict All Test Samples
Y_pred = model.predict(test_data)
print("Prediction probabilities, first 10 samples:")
print(Y_pred[:10])
y_pred_classes = np.argmax(Y_pred, axis=1)
y_true = test_data.classes
class_labels = list(test_data.class_indices.keys())

#Confusion Matrix & Classification Report
#Confusion Matrix: Shows how many images of each class were classified correctly vs. misclassified.
#Classification Report: Gives precision, recall, F1-score for each class

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
conf_mat = confusion_matrix(y_true, y_pred_classes)
plt.figure(figsize=(6,6))
sns.heatmap(conf_mat, annot=True, fmt='d', cmap='Blues', xticklabels=class_labels, yticklabels=class_labels)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

print("\nClassification Report:\n")
print(classification_report(y_true, y_pred_classes, target_names=class_labels))

from PIL import Image
#visualise predictions few of them to show side-by-side how well predictions match reality on sample test images.

import random
filepaths = test_data.filepaths
indices = random.sample(range(len(filepaths)), 16)

plt.figure(figsize=(12,12))
for i, idx in enumerate(indices):
    img = Image.open(filepaths[idx])
    true_label = class_labels[y_true[idx]]
    pred_label = class_labels[y_pred_classes[idx]]
    plt.subplot(4,4,i+1)
    plt.imshow(img)
    plt.title(f"T:{true_label}, P:{pred_label}", fontsize=8)
    plt.axis('off')
    print(f"Plot {i+1}: {filepaths[idx]} (T:{true_label}, P:{pred_label})")
plt.tight_layout()
plt.show()